{% set version = "3.2.9" %}

package:
  name: biasaway
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/b/biasaway/biasaway-{{ version }}.tar.gz
  sha256: "bccd9e988dc30324be07fef9a5c756740567a45ee0e53af09b13e9461805350e"

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - biopython
    - numpy
    - matplotlib-base
    - seaborn
    - cyushuffle
    - scikit-learn

test:
  imports:
    - biasaway
  commands:
    - biasaway --help
    - biasaway k --help
    - biasaway w --help
    - biasaway c --help
    - biasaway g --help

about:
  home: https://bitbucket.org/CBGR/biasaway
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: "BiasAway: a tool to generate composition-matched background sequences"
  description: "BiasAway provides user with four models for generating background sequences useful to enrichment analyses. These backgrounds derived from mono- and di- nucleotide shuffled sequences, and genomic sequences matched to the GC content of the target data."
  doc_url: 'https://biasaway.rtfd.io'

extra:
  recipe-maintainers:
    - asntech
